### ISSUE TITLE
我的web应用使用swoole(常驻内存)，hrpose服务器重启时，导致出现 response read error

### ISSUE THREAD

**Issue by mrzxy** [hprose/hprose-php#102]
原因应该是 内存cache了stream客户端，当rpc服务器重启时，原有client连接中断
有什么解决办法吗？比如如何手动重载steam_client什么的

**Comment by andot** [comment]
这很正常啊，重新发起调用就行了。

**Comment by mrzxy** [comment]
晕，谢谢提醒，忘了用了单例
