### ISSUE TITLE
pecl install hprose 报错

### ISSUE THREAD

**Issue by akaQin** [hprose/hprose-php#115]
安装hprose扩展，编译hprose_common.lo文件时报错，貌似7.1以上的php版本安装都会报这个错
系统版本：
Linux 78fab336ae08 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
php版本：
 7.3
扩展安装情况：

> RUN apt-get update \
    && apt-get install -y \
      vim \
      git \
      zip \
      wget \
      libz-dev \
      libssl-dev \
      libpcre3-dev \
    && apt-get clean \
    && apt-get autoremove \
    && docker-php-ext-install bcmath \
    && docker-php-ext-install sockets \
    && docker-php-ext-install pdo_mysql \
    && pecl install -o -f redis \
    && docker-php-ext-enable redis \
    && rm -rf /tmp/*

# Swoole extension
RUN wget https://github.com/swoole/swoole-src/archive/v4.3.3.tar.gz -O swoole.tar.gz \
    && mkdir -p swoole \
    && tar -xf swoole.tar.gz -C swoole --strip-components=1 \
    && rm swoole.tar.gz \
    && ( \
    cd swoole \
    && phpize \
    && ./configure --enable-async-redis --enable-mysqlnd --enable-openssl --enable-http2 \
    && make -j$(nproc) \
    && make install \
    ) \
    && rm -r swoole \
    && docker-php-ext-enable swoole

这是我遇到的报错信息：

> creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/bash /tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/libtool --mode=compile cc  -I. -I/tmp/pear/temp/hprose -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/include -I/tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/main -I/tmp/pear/temp/hprose -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/hprose/php_hprose.c -o php_hprose.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/hprose -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/include -I/tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/main -I/tmp/pear/temp/hprose -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/hprose/php_hprose.c  -fPIC -DPIC -o .libs/php_hprose.o
/bin/bash /tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/libtool --mode=compile cc  -I. -I/tmp/pear/temp/hprose -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/include -I/tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/main -I/tmp/pear/temp/hprose -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/hprose/hprose_common.c -o hprose_common.lo
 cc -I. -I/tmp/pear/temp/hprose -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/include -I/tmp/pear/temp/pear-build-defaultuserTioZT3/hprose-1.6.6/main -I/tmp/pear/temp/hprose -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/hprose/hprose_common.c  -fPIC -DPIC -o .libs/hprose_common.o
/tmp/pear/temp/hprose/hprose_common.c: In function '__get_fcall_info_cache':
/tmp/pear/temp/hprose/hprose_common.c:202:8: error: 'zend_fcall_info_cache {aka struct _zend_fcall_info_cache}' has no member named 'initialized'
     fcc.initialized = 1;
        ^
/tmp/pear/temp/hprose/hprose_common.c: In function '__create_php_object':
/tmp/pear/temp/hprose/hprose_common.c:764:12: error: 'zend_fcall_info_cache {aka struct _zend_fcall_info_cache}' has no member named 'initialized'
         fcc.initialized = 1;
            ^
Makefile:196: recipe for target 'hprose_common.lo' failed
make: *** [hprose_common.lo] Error 1
ERROR: `make' failed

**Comment by Soft-me** [comment]
一样的问题

**Comment by andot** [comment]
该问题已修复
