### ISSUE TITLE
无故出行wrong Response

### ISSUE THREAD

**Issue by ANWSY** [hprose/hprose-php#120]
本来在另一个环境是ok的，复制项目到另一个环境，客户端访问服务端，服务端的返回是有的，不过格式不对，一直是报错的，查了代码，没发现哪里有什么问题，求助各位大佬
![image](https://user-images.githubusercontent.com/13809509/66446434-1a9fc280-ea7d-11e9-8a36-19fb71da4fe8.png)

**Comment by ANWSY** [comment]
大佬，原因应该就是出在这个响应数据带红点的问题上，这个红点能去掉吗

**Comment by andot** [comment]
去掉php文件中UTF-8的BOM。

**Comment by ANWSY** [comment]
好的，谢谢，我这边去掉后就能正常使用了
