### ISSUE TITLE
MongoDB\BSON\UTCDateTime 类序列化错误

### ISSUE THREAD

**Issue by dotpub** [hprose/hprose-php#126]
使用TCP协议，hprose-php 2.0版本，php调用RPC服务器端返回 MongoDB\BSON\UTCDateTime 对象时，原来的时间会变化为调用时间。该对象的结构是{"$date":{"$numberLong":"1536727130944"}}，$numberLong在每次调用时都会变化。

**Comment by andot** [comment]
大概这个 $numberLong 属性是只读属性，不能被序列化。

**Comment by dotpub** [comment]
序列化后是这样的：
`s10"createTime"c24"MongoDB_BSON_UTCDateTime"{}o0{}`
该对象是MongoDB的驱动提供的用C写的，所以该类通过反射获取后没有任何属性。

我返回时做类型转换吧。

**Comment by andot** [comment]
嗯，好的
