### ISSUE TITLE
我用192.168.1.79的ip搭建了一个server，用192.168.1.4作为client 请求时，返回了这样的结果

### ISSUE THREAD

**Issue by fucongcong** [hprose/hprose-php#14]
Exception: Success in /home/share/cc/vendor/hprose/hprose/src/Hprose/Swoole/Socket/Client.php:139

**Comment by fucongcong** [comment]
我用192.168.1.79使用client是可以成功的。

**Comment by andot** [comment]
看上去像是出错之后没有返回错误码造成的，这个应该是 swoole 的问题。

**Comment by fucongcong** [comment]
支持php7么 192.168.1.4是php7的环境

**Comment by andot** [comment]
hprose 是支持，swoole 是否支持不清楚。

**Comment by fucongcong** [comment]
请教一下，如果我想要更新server端的代码的时候，还有进程在处理，此时重启server，这些进程会停掉么

**Comment by andot** [comment]
会的

**Comment by fucongcong** [comment]
不支持热重启么

**Comment by fucongcong** [comment]
问题已解决～～

**Comment by andot** [comment]
嗯，设置成 public 的啦。
