### ISSUE TITLE
socket服务器中，偶发性的报错：(Exception(code: 0): Packets out of order. Expected 1 received 0. Packet size=145 at /home/wwwroot/api_test/vendor/hprose/hprose/src/Hprose/Client.php:383)，基本上每天第一次访问都会出现

### ISSUE THREAD

**Issue by lbw153** [hprose/hprose-php#158]
错误日志：
[2024-08-07 09:33:46] local.ERROR: Packets out of order. Expected 1 received 0. Packet size=145 {"userId":2,"exception":"[object] (Exception(code: 0): Packets out of order. Expected 1 received 0. Packet size=145 at /home/wwwroot/api_test/vendor/hprose/hprose/src/Hprose/Client.php:383)
[stacktrace]
#0 /home/wwwroot/api_test/vendor/hprose/hprose/src/Hprose/Client.php(477): Hprose\\Client->decode()
#1 /home/wwwroot/api_test/vendor/hprose/hprose/src/Hprose/Client.php(489): Hprose\\Client->syncInvokeHandler()
#2 /home/wwwroot/api_test/vendor/hprose/hprose/src/Hprose/Client.php(103): Hprose\\Client->invokeHandler()
#3 /home/wwwroot/api_test/vendor/hprose/hprose/src/Hprose/Client.php(608): Hprose\\Client->Hprose\\{closure}()
#4 /home/wwwroot/api_test/vendor/hprose/hprose/src/Hprose/Client.php(438): Hprose\\Client->invoke()
#5 /home/wwwroot/api_test/app/Library/RpcClient.php(26): Hprose\\Client->__call()
#6 /home/wwwroot/api_test/app/Http/Logic/Cockpit/SiteLogic.php(66): App\\Library\\RpcClient->__call()
#7 /home/wwwroot/api_test/app/Http/Controllers/Cockpit/SiteController.php(97): App\\Http\\Logic\\Cockpit\\SiteLogic->home()
#8 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Cockpit\\SiteController->home()
#9 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#10 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#11 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#12 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#13 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#14 /home/wwwroot/api_test/app/Http/Middleware/Permission.php(96): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\Permission->handle()
#16 /home/wwwroot/api_test/app/Http/Middleware/RepeatRequest.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RepeatRequest->handle()
#18 /home/wwwroot/api_test/app/Http/Middleware/Annotation.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\Annotation->handle()
#20 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#22 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#24 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#25 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#26 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#28 /home/wwwroot/api_test/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#30 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/wwwroot/api_test/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#32 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#33 /home/wwwroot/api_test/app/Http/Middleware/TokenExpire.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\TokenExpire->handle()
#35 /home/wwwroot/api_test/app/Http/Middleware/QueryAuth.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\QueryAuth->handle()
#37 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#39 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#40 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#41 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#42 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#43 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#44 /home/wwwroot/api_test/app/Http/Middleware/SetProxyIp.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\SetProxyIp->handle()
#46 /home/wwwroot/api_test/app/Http/Middleware/SetLang.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\SetLang->handle()
#48 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#51 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#53 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#55 /home/wwwroot/api_test/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#57 /home/wwwroot/api_test/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#59 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#61 /home/wwwroot/api_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#62 /home/wwwroot/api_test/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()
#63 {main}
"}

**Comment by xinlongnews** [comment]
邮件已收到！
