### ISSUE TITLE
支持php7吗

### ISSUE THREAD

**Issue by wmydz1** [hprose/hprose-php#17]
Fatal error: Uncaught Error: Class 'swoole_http_server' not found in /Library/WebServer/Documents/hprose-php/src/Hprose/Swoole/Http/Server.php:27 Stack trace: #0 /Library/WebServer/Documents/hprose-php/src/Hprose/Swoole/Server.php(58): Hprose\Swoole\Http\Server->__construct('127.0.0.1', 10000, 'SWOOLE_PROCESS') #1 /Library/WebServer/Documents/hprose-php/src/Hprose/Swoole/Server.php(90): Hprose\Swoole\Server->init_server('http://127.0.0....') #2 /Library/WebServer/Documents/hprose-php/demo/server.php(13): Hprose\Swoole\Server->__construct('http://127.0.0....') #3 {main} thrown in /Library/WebServer/Documents/hprose-php/src/Hprose/Swoole/Http/Server.php on line 27

**Comment by andot** [comment]
支持，你要用 swoole 服务的话，需要安装 swoole 扩展。可以通过：

    pecl install swoole

方式来安装，另外还可以安装 hprose 扩展来加速序列化反序列化，安装方式是：

    pecl install hprose
