### ISSUE TITLE
RPC场景下,如何从客户端发送cookie到服务端?

### ISSUE THREAD

**Issue by ouerzc** [hprose/hprose-php#21]
如题:
RPC场景下,如何从客户端发送cookie到服务端?

**Comment by andot** [comment]
hprose 会自动传递服务器端设置的 cookie，用户不能自己从客户端发送 cookie 到服务器。

**Comment by ouerzc** [comment]
好的,谢谢

**Comment by andot** [comment]
不客气。这样做有两个原因，第一个原因是并非所有平台提供的 HTTP 通讯都支持让用户设置 Cookie，比如在浏览器中，使用 XHR 虽然可以设置一些自定义的 HTTP 头，但是是不能设置 `Cookie` 的。第二个原因是 hprose 支持多种底层传输协议，所以用户在构建服务时，最好是不要依赖某个特定传输协议的功能，能直接使用 RPC 方式传递的数据，尽量使用 RPC 方式传递，这样可以方便底层协议替换。
