### ISSUE TITLE
hprose 和 hprose-php 有什么区别？

### ISSUE THREAD

**Issue by reatang** [hprose/hprose-php#23]

**Comment by andot** [comment]
能把问题说的清楚一点吗？

**Comment by reatang** [comment]
谢谢，您回答的就是我想知道的。

**Comment by reatang** [comment]
有一个问题：
我的自动加载是composer

//服务端：
$server = new Server('http');
$server->addClassMethods("HproseApi\\Apis\\HelloWorld");
$server->start();

class HelloWorld
{
    public function hello($name)
    {
        return "Hello $name !";
    }

}

// 客户端
$client = new Client('http://l-tmp.l.org/hprose/server.php');
$promise = $client->hello('reatang');

客户的一直在报错：
call_user_func_array() expects parameter 1 to be a valid callback, non-static method HproseApi\Apis\HelloWorld::hello() should not be called statically

虽然把hello() 改为静态的就好了，不过这不太对啊。

我在找问题的时候发现在类Hprose\Server的307行调用$this->callService($args, $context) 已经成功的获取到执行后的数据了，那么是在哪步报错的呢？

**Comment by andot** [comment]
addClassMethods 发布的就是静态方法，实例方法你要创建实例对象，并且用 addInstanceMethods 来发布。

**Comment by reatang** [comment]
谢谢，还是希望能有注释

**Comment by andot** [comment]
这些内容会单独写到文档里的。
