### ISSUE TITLE
用了httpserver和httpclient做测试，然后报错了

### ISSUE THREAD

**Issue by kkshow** [hprose/hprose-php#26]
代码都是直接从readme里面取的，稍微调整了一下，server正常，client报错了

server
```
<?php
require_once('hprosesrc\Hprose.php');

function hello($name) {
	return 'Hello ' . $name;
}

$server = new HproseHttpServer();
$server->addFunction('hello');
$server->start();
```

client
```
<?php
require_once('hprosesrc\Hprose.php');
$client = new HproseHttpClient('http://127.0.0.1/helloserver.php');
echo $client->hello('World');
```

错误提示
```
Object of class Hprose\Future could not be converted to string
```

环境是windows php5.4.16

**Comment by andot** [comment]
你复制到是旧的 README 的代码，新的 README 中并没有代码。

新版本的文档在这里：https://github.com/hprose/hprose-php/wiki

你的客户端代码只需要这样修改一下就可以了：

```php
<?php
require_once('hprosesrc\Hprose.php');
$client = new HproseHttpClient('http://127.0.0.1/helloserver.php', false);
echo $client->hello('World');
```

**Comment by kkshow** [comment]
吐血，加了个参数果然可以了，我看的是这个路径 [https://github.com/hprose/hprose-php/tree/87a4e1bdc5b360096634b3a3f8d49074643624a3](https://github.com/hprose/hprose-php/tree/87a4e1bdc5b360096634b3a3f8d49074643624a3) 和doc文档里面的案例。

这个最好还是统一一下比较好。

**Comment by andot** [comment]
你看的是 github 的历史记录，历史的内容改不了。

**Comment by yesterday679** [comment]
@andot   对于THINKPHP这种框架，怎么加入controller中的method呢？

**Comment by andot** [comment]
发布的服务最好单独编写，把 Controller 中的方法发布为服务这种做法是不合适的。
