### ISSUE TITLE
如何给hprose的server做守护进程daemon?

### ISSUE THREAD

**Issue by forgottener** [hprose/hprose-php#27]
如题,像swoole的server是可以设置参数`"daemonize" => true` ,那么hprose呢?

**Comment by andot** [comment]
一样的，你同样做这样的设置就可以了。

**Comment by forgottener** [comment]
在hprose/hprose-php里全文搜索了'daemon',没有这个设置项吧?

**Comment by andot** [comment]
是 swoole 的设置，使用 hprose-swoole 就可以了。

**Comment by forgottener** [comment]
解决了,参考http://rango.swoole.com/archives/59  加个daemonize的方法
function daemonize()
{
        $pid = pcntl_fork();
        if ($pid == -1) {
            die("fork(1) failed!\n");
        } elseif ($pid > 0) {
            //让由用户启动的进程退出
            exit(0);
        }
        //建立一个有别于终端的新session以脱离终端
        posix_setsid();
        $pid = pcntl_fork();
        if ($pid == -1) {
            die("fork(2) failed!\n");
        } elseif ($pid > 0) {
            //父进程退出, 剩下子进程成为最终的独立进程
            exit(0);
        }
}
daemonize();
$server = new Server("tcp://0.0.0.0:1314");
$server->addFunction("hello");
$server->start();

**Comment by andot** [comment]
原来你用的是 `Hprose\Socket\Server` 啊，这个 server 是为了方便在 windows 下调试用的，所以没用 pcntl 这个扩展。
