### ISSUE TITLE
测试通讯失败

### ISSUE THREAD

**Issue by inteye** [hprose/hprose-php#30]
> require_once "vendor/autoload.php";
> use Hprose\Http\Server;
> function hello($name) {
>     return "Hello " . $name;
> }
> $server = new Server();
> $server->addFunction("hello");
> $server->start();

> require_once "vendor/autoload.php";
> use Hprose\Http\Client;
> use Hprose\InvokeSettings;
> use Hprose\ResultMode;
> $client = new Client('http://order.local/s.php', false);
> echo $client->hello("docker", new InvokeSettings(array('mode' => ResultMode::Normal)));

**不通，可能是哪错了？服务器地址正式环境可用**

**Comment by andot** [comment]
在你的客户端所在的电脑上打开浏览器，输入你的服务器地址。如果你的浏览器打不开，请检查你的地址是否输入正确，或者你是否开了防火墙把该服务给屏蔽了，或者你的网线是否插好了，诸如此类的问题我就不再一一列举并给出解决方案了。
