### ISSUE TITLE
用Tcp方式连接通讯，执行服务端报错，怎么解决的呢

### ISSUE THREAD

**Issue by guiguoershao** [hprose/hprose-php#31]
socket_import_stream() expects parameter 1 to be resource, boolean given in
这是什么问题呢？ #

class Hello
{
    public function say($name)
    {
        return 'Hello '.$name;
    }
}

use Hprose\Socket\Server;

$server = new Server("tcp://127.0.0.1:8000");

$server->add((new Hello()));

$server->debug = true;

$server->start();

**Comment by guiguoershao** [comment]
`class Hello
{
    public function say($name)
    {
        return 'Hello '.$name;
    }
}

use Hprose\Socket\Server;

$server = new Server("tcp://127.0.0.1:8000");

$server->add((new Hello()));

$server->debug = true;

$server->start();`

**Comment by andot** [comment]
```php
<?php
require_once "../../vendor/autoload.php";

use Hprose\Socket\Server;

function hello($name) {
    return "Hello $name!";
}
$server = new Server("tcp://0.0.0.0:1314");
$server->setErrorTypes(E_ALL);
$server->setDebugEnabled();
$server->addFunction('hello');
$server->start();
```

运行没有问题。你的错误这里没法重现啊
