### ISSUE TITLE
thinkphp支持

### ISSUE THREAD

**Issue by yangweijie** [hprose/hprose-php#37]
thinkphp框架 有 [扩展](https://github.com/top-think/thinkphp/tree/master/ThinkPHP/Library/Vendor/Hprose) 能否加入官方，并提供示列和文档

**Comment by andot** [comment]
TP3 框架的那个扩展是错误的用法。服务本身不应该写在控制器中，而应该单独写成服务类，控制器只作为服务发布的接口，而 Hprose 本身就支持这种用法，所以 TP 的那个扩展是没有用的，而且是有害的。
