### ISSUE TITLE
不支持php 7.1?

### ISSUE THREAD

**Issue by icekingcy** [hprose/hprose-php#43]
在7.1.5下运行 没有任何反应 也不报错

**Comment by andot** [comment]
你可能少装了某些扩展，比如 mbstring 之类的。最好安装一下 hprose 扩展，不但可以避免此类问题，还可以起到加速的作用。

**Comment by lishuaidb** [comment]
php7.1 下, 异步客户端Future\co 没有返回结果

**Comment by andot** [comment]
有。co 的返回结果也是一个 Future 对象。

**Comment by lampsunny** [comment]
> hprose 扩展

hprose 扩展的扩展有吗？

**Comment by andot** [comment]
有
