### ISSUE TITLE
Laravel 自关联的数据，在客户端无法解析

### ISSUE THREAD

**Issue by Luminee** [hprose/hprose-php#44]
如果一个方法，返回值是 一个数据对象 ModelA $a，它的一个属性 还是这个类 ModelA 构成的数据对象 $b， 那么这个返回结果在客户端就无法解析，报错为 
`Unexpected serialize tag '{' in stream`

实例代码如下：

Server：
```
public function testConnection()
    {
        $label = Label::find(1);
        $label->child = Label::find(2);
        return $label;
    }
```
请问应当如何解决。

**Comment by andot** [comment]
Laravel 的类中，包含了许多不可序列化的类型，因此不能直接传递。

**Comment by Liv1020** [comment]
服务中最好入参和出参都是简单数据类型，类很少能在分布式系统中完全重用，尤其是model

**Comment by andot** [comment]
另外，你还可以安装一下 hprose 扩展试试看能不能解决自关联数据的问题。php 语言本身对于对象引用的比较很难做，但是在扩展中反而会方便一些，所以，对于引用的处理，hprose 扩展版本中实现的序列化反序列化要比 php 版本好一些，性能也会有很明显的提升。

**Comment by Luminee** [comment]
多谢指导，我会去调整项目，改为使用简单数据。
