### ISSUE TITLE
push 之后 服务端显示发送成功, 客户端没有收到消息是怎么回事儿?

### ISSUE THREAD

**Issue by lishuaidb** [hprose/hprose-php#46]

**Comment by andot** [comment]
hprose的推送，在发送成功时，不会显示信息，所以你说的发送成功的信息是你自己写的，所以为什么客户端没收到我也不知道。

**Comment by lishuaidb** [comment]
我是在unsubscribe的回调里写的broadcast, callback里显示success, 但是客户端经常收不到广播的内容, 是这种写法不对么
