### ISSUE TITLE
服务有多个返回值时

### ISSUE THREAD

**Issue by aaa3096** [hprose/hprose-php#47]
当服务有多个返回值时，同步调用时，php怎么接收多个返回值？

**Comment by andot** [comment]
php 得到的是一个数组。数组的第一个元素是第一个返回值，第二个元素是第二个返回值。如果你的多值返回（go语言的）中最后一个参数是error类型，这个结果不会已返回结果数组中的元素表示，而是当error为null时，不存在这个结果，当error不为空时，客户端得到异常。
