### ISSUE TITLE
创建了httpclient发现请求是以post方式发送的，怎么转程get请求发送呢？

### ISSUE THREAD

**Issue by xingxing55** [hprose/hprose-php#51]
new \Hprose\Http\Client($uri, false)创建了一个客户端，但发现请求是post方式发送的，问题是post请求在框架中是要签名认证的，所以有以下两点疑问
1.$this->client->invoke($name, $param)这样调用远程方法  如何带上签名，并且在远程方法$_POST[‘签名’]有值
2.获取改变请求方式为GET?

**Comment by andot** [comment]
hprose 的请求都是 POST 发送的，没有 GET 请求方式。hprose 请求不是普通的 "multipart/form-data" 表单请求，所以在 PHP 服务器端是不存在 $_POST[] 这样的数据的。

据我说知，目前大部分常用的框架都是支持跟 hprose 无缝整合的。不知道你用的是什么框架而必须要用到签名认证。

**Comment by xingxing55** [comment]
您好，我用的symfony2.*框架，因为该框架默认情况下，会对所有POST请求都会验证csrf_token，现在的问题就是使用hprose  httpserver 就会导致请求被禁止访问，通常为了安全，都会对post进行csrf_token验证，这个问题在正常使用hprose httpserver 和 不取消对post csrf_token验证的情况下，有解决的办法吗？请赐教，谢谢。

**Comment by andot** [comment]
有个专门的 https://github.com/hprose/hprose-symfony 版本
