### ISSUE TITLE
关于文档章节 - Hprose 客户端 的疑问

### ISSUE THREAD

**Issue by wukonggege** [hprose/hprose-php#52]
“Hprose 客户端” 一节提到了 onError 事件和 onFailswitch 事件，但是并没有讲如何注册该事件。
另外，关于“onError 事件”有这样一句描述：“当客户端采用回调方式进行调用时，并且回调函数没有参数，如果发生异常，该事件会被调用”，什么叫“回调函数没有参数”，没有设置参数？没有传回参数？，这里的参数指的是 callback 函数的 $args 形参还是整个 callback 函数的参数？

**Comment by andot** [comment]
onError 和 onFailswitch 事件与普通属性一样，直接给其赋值就可以了，可以赋值为函数、方法或者匿名函数。如果赋值为 NULL，则表示取消该事件。

回调函数没有参数是指回调函数的形式为:

```php
function callback() {...}
```

这个文档 invoke 方法一节有明确写出来。
