### ISSUE TITLE
关于TCPSERVER 的疑问

### ISSUE THREAD

**Issue by xingxing55** [hprose/hprose-php#53]
最近项目使用hprse tcp server 后，server 进程不怎么稳定，总是每个两三天客户端就调用不了服务端的方法，登陆到服务器查看server 进程没什么异常，进程依然处于正常监听状态。奇怪的事，杀死server 进程，再重启进程，一切又正常了，这个问题困绕了我很久了，会不会是因为程序中使用exit die之类？或者是其他的问题？请赐教，非常感谢！

**Comment by andot** [comment]
hprose 的服务里确实不应该有 exit 和 die 这样的语句。不过如果有这样的语句执行到它们的时候，应该是整个服务就退出了，所以应该不是这个问题。另外，tcp server 最好用 swoole 版本的做服务器，stream 版本只是用来方便在 windows 开发环境下做测试用的。
