### ISSUE TITLE
hprose-php服务器启动后，rpc引入的php类文件，被修改了，如何reload?

### ISSUE THREAD

**Issue by wuchuguang** [hprose/hprose-php#55]
server启动用，引入了A.php文件，后面再改这个A.php文件，不会自动reload这个改后文件。有没有现在的reload?或解决方案？现在的处理是重新启动服务器

**Comment by andot** [comment]
如果你用的是 fpm-php，不会有 reload 问题。如果你使用的是 swoole，可以去 swoole 官方文档里看一下，里面有关于 swoole 热启动的介绍。
