### ISSUE TITLE
在yaf中 使用hprose 当 return 字符串时 会产生警告

### ISSUE THREAD

**Issue by pan269** [hprose/hprose-php#59]
我注意到是由于  Hprose\Future 中 100行~101行
if (($value !== NULL) and is_object($value) or is_string($value)) {
            if (method_exists($value, 'then')) {
导致的
这是一个很棒的设计  但我觉得yaf 中的自动载入也是合理的  
能否把  or is_string($value) 去掉

**Comment by andot** [comment]
$value 可能是类名，所以这里才会有这个判断。

**Comment by pan269** [comment]
我也注意到了这点   
我觉得当  is_string($value)  时可以先用class_exists($value,false)先检查类是否存在然后再检查 method_exists($value, 'then')    

说实话  Promise 异步编程这章 我没这么看懂....

**Comment by andot** [comment]
一会儿我把它去掉吧。

**Comment by pan269** [comment]
好的 多谢了
