### ISSUE TITLE
客户端用完要不要关闭？

### ISSUE THREAD

**Issue by zouhuigang** [hprose/hprose-php#61]
use Hprose\Client;
$client = Client::create('http://127.0.0.1:9999/', false);
var_dump($client->hello("world"));
$inputFileName='/nfs_file/sites/sys'.'/m/pingan/excel/8m.xlsx';//$_SERVER['DOCUMENT_ROOT']解析一个8M的excel
print_r($client->readExcel($inputFileName,0,68964,5));
echo "sss";die;

**Comment by Liv1020** [comment]
不用，但是你需要注意输出的内存

**Comment by zouhuigang** [comment]
好的，谢谢！
