### ISSUE TITLE
使用代理之后,php的hprose无法使用,报错如下...是什么原因呢?

### ISSUE THREAD

**Issue by zzlphp** [hprose/hprose-php#63]
Fatal error: Uncaught Exception: Wrong Response: 
HTTP/1.1 200 OK
Server: nginx/1.10.0
Date: Thu, 16 Nov 2017 00:44:51 GMT
Content-Type: text/plain;charset=UTF-8
Content-Length: 2172
Connection: keep-alive
X-Powered-By: PHP/7.1.9
Set-Cookie: PHPSESSID=dbcu4en8r14a2251gldpfivo49; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache

Rm2{s4"code"s3"200"s4"data"m9{s5"total"i122;s8"per_page"i10;s12"current_page"1s9"last_page"i13;s13"next_page_url"s8"/?page=2"s13"prev_page_url"ns4"from"1s2"to"i10;r3;a10{m13{s2"id"i176;s2"ip"s15"180.173.234.115"s4"uuid"s12"zhangziliang"s6"shared"s3"yes"s6"showed"1s4"href"s28"https://sspai.com/post/33299"s4"time"ns11"description"s44"通过终端命令改变 Launchpad 中应用图标的大小丨一日一技 · Mac - 少数派"s8"extended"es3"tag"es4"hash"ns4"meta"ns11"update_time"i1510706688;}m13{r16;i175;r17;r18;r19;r20;r21;r22;r23;1r24;s18"https://wxvip.org/"r26;nr27;s9"wxvip.org"r29;er30;s9"wechat wx"r31;nr32;nr33;i15106 in /Users/ziziliang/Google 云端硬盘/alfred/Alfred.alfredpreferences/workflows/user.workflow.BB9BF069-D107-4B0F-9034-2FAFA2F39327/vendor/hprose/hprose/src/Hprose/Client.php on line 374

**Comment by andot** [comment]
你的代理服务器把 HTTP 头当成数据给转发了。
