### ISSUE TITLE
超时是否有改善空间？怎么改善？序列化？

### ISSUE THREAD

**Issue by ycaihappy** [hprose/hprose-php#64]
PHP Fatal error:  Uncaught exception 'Exception' with message '28: Operation timed out after 31013 milliseconds with 0 out of -1 bytes received' in

**Comment by andot** [comment]
1、如果返回的数据很大且复杂，比如返回一个几万条记录的对象数组，你可以通过安装 hprose 的 pecl 扩展来有效的改善序列化反序列化的性能。
2、检查一下服务中是否有比较耗时的操作，对这些操作本身进行优化。
3、检查服务中是否有导致死锁的代码。
4、如果你使用 swoole 做服务器，请不要使用 swoole 2.0 的协程功能，它不支持 PHP 内建的动态函数和方法调用（比如 call_user_func、call_user_func_array、__call、__invoke 等），会导致死锁的产生。
