### ISSUE TITLE
序列化长度计算是不是不准？

### ISSUE THREAD

**Issue by ycaihappy** [hprose/hprose-php#69]
strlen(iconv('UTF-8', 'UTF-16LE', $s)) >> 1; 

上面这个算长度的，某些情况下会为0。命令行执行为0，浏览器执行为正确的值。

导致请求的时候失败。

**Comment by ycaihappy** [comment]
代码所在位置 hprose/Hprose/Writer.php

**Comment by andot** [comment]
如果是 0 的话，说明你的 $s 的编码不是 utf-8 编码。

**Comment by andot** [comment]
另外，这个php版本的序列化实现仅仅是为了在不安装扩展的情况下可用，但是在实际使用时，推荐安装 hprose 的序列化扩展，那样效率会高很多。
