### ISSUE TITLE
异常处理

### ISSUE THREAD

**Issue by xuzili1993** [hprose/hprose-php#71]
请问下使用的时候，客户端参数传输错误导致服务端异常退出，try cactch 无法捕获异常，onSendError也处理不了，请问下有什么解决方案吗

```
require __DIR__.'/../vendor/autoload.php';
use Hprose\Swoole\Server;
function a($b, $c) {
    echo $b;
    echo  $c;
}

    $server = new Server("tcp://0.0.0.0:1314");
    $server->setDebugEnabled(true);
    dump($server->isDebugEnabled());
    $server->addFunction('a');
    $server->onSendError = function ($error, \stdClass $context) {
        dump($error->getMessage());
        return true;
    };
    $server->start();


    $client = \Hprose\Client::create('tcp://127.0.0.1:1314', false);
    return $client->a(['name' => 'xz'],  new InvokeSettings(array('mode' => ResultMode::Normal)));
```

**Comment by andot** [comment]
服务器不应该使用 echo, dump 等输出的语句。

**Comment by xuzili1993** [comment]
@andot 在客户端进行try catch还是会导致服务端的异常退出。

````
  $client = \Hprose\Client::create('tcp://workspace:1314', false);
    try {
        return $client->a(['name' => 'xz'],  new InvokeSettings(array('mode' => ResultMode::Normal)));
    } catch (\Exception $exception) {
        dd($exception);
    }
````

![image](https://user-images.githubusercontent.com/13882228/36515313-9b7f34c4-17b3-11e8-87bb-35ed25b9cccc.png)

**Comment by andot** [comment]
我试着修复了一下，你帮忙测试一下，看看还有没有这个问题。

**Comment by andot** [comment]
@RootYQ 你在服务器端已经捕获了的异常就不会返回给客户端了，只有你调用的远程调用中没有被捕获的调用才会传给客户端。

**Comment by RootYQ** [comment]
@andot 比如这样一个例子
**Server端：**
```
<?php
require_once 'vendor/autoload.php';

use Hprose\Swoole\Server;

function hello($name)
{
    try {
        $a = 1 / 0;
    } catch (Exception $exception) {
        var_dump($exception);
    }

    return "Hello $name!";
}

$server = new Server("tcp://0.0.0.0:8088");
$server->addFunction('hello');
$server->start();
```

**client端：**

```
<?php
require_once 'vendor/autoload.php';

use Hprose\Socket\Client;

$client = new Client('tcp://127.0.0.1:8088', false);
$result = $client->hello('word');

echo $result;
```
1 / 0这种php的是会报`E_WARNING `错误，这种错误不是异常，try catch不能捕获 ，laravel框架对这种错误使用`set_error_handler`捕获封装成可捕获的异常，但是hprose也有`set_error_handler`设置了错误捕捉，覆盖了laravel错误处理逻辑

**Comment by andot** [comment]
laravel 也是把错误输出到客户端（浏览器端），hprose 同样是把错误输出到客户端，有什么区别吗？而且 hprose 捕获的错误，你在服务器端还可以处理，比如 通过设置 onSendError 事件，把错误记录到服务器端的日志文件中，或者你也可以通过设置 errorTypes 属性来忽略 notice 或者 warning 等错误。

**Comment by RootYQ** [comment]
@andot 我感觉上面两个方案好像都不能解决我的问题（也可能是我理解不到位），我试着再说明一下
**laravel的错误处理机制**
```
public function handleError($level, $message, $file = '', $line = 0, $context = [])
{
    if (error_reporting() & $level) {
        throw new ErrorException($message, 0, $level, $file, $line);
    }
}
```
\Hprose\Service::__construct 的代码为：
```
public function __construct() {
    parent::__construct();
    $this->errorTypes = error_reporting();
    register_shutdown_function(array($this, 'fatalErrorHandler'));
    $this->addMethod('getNextId', $this, '#', array('simple' => true));
    self::$_lastErrorHandler = set_error_handler(array($this, 'errorHandler'), $this->errorTypes);
}

public function errorHandler($errno, $errstr, $errfile, $errline) {
    if (self::$trackError) {
        self::$lastError = new ErrorException($errstr, 0, $errno, $errfile, $errline);
    } else if (self::$_lastErrorHandler){
        call_user_func(self::$_lastErrorHandler, $errno, $errstr, $errfile, $errline);
    }
}
```

如果按照`set_error_handler` 的覆盖策略：后面会覆盖之前的设置的，然后返回上一个设置的函数

那么结合上面
> https://github.com/hprose/hprose-php/issues/71#issuecomment-438658352
我写的这个例子的话，程序的逻辑就发生了变化：

laravel：`E_WARNING`错误触发`handleError`函数，包装成异常会被throw出去，**这样程序不会再往下执行**。
hprose：set_error_handler重新设置成`errorHandler`, 包装成异常赋值给静态变量，**这样做的话此时程序会继续执行**，这样我就没办法捕获这种封装的异常，去做一些其他业务逻辑，我不知道如何改变errorTypes和设置onSendError能够影响这一行为，希望指点迷津，🙏

**Comment by andot** [comment]
哦，大概明白你的意思了，你是希望用 try catch 来捕获本来不能捕获的异常，而这个行为是建立在 laravel的错误处理机制上的，而不是 php 本来的行为。所以，你希望能够得到 laravel 方式的错误处理，以便你能够用 try catch 来捕获本来不能捕获的异常，是这样的吧？

如果你的需求是这样的，那你只需要在创建 hprose 服务器之后，重新执行一下 set_error_handler 方法，把错误处理设置为你 laravel 方式的错误处理函数就行了。这样不就可以把 hprose 服务器设置的错误处理给重新覆盖了吗？

而且这个只会覆盖普通的错误处理，崩溃性的错误处理不受影响，仍然按照 hprose 的方式来，因为那些崩溃性错误不管用什么方式也没办法用 try 来捕获。
