### ISSUE TITLE
订阅后周期性的swoole_timer_clear()错误

### ISSUE THREAD

**Issue by zhangchn** [hprose/hprose-php#73]
一个hprose swoole的订阅topic，现象是每两分钟会出现一次swoole_timer_clear()的错误，timer id没有找到。

怀疑是Service.php里，publish()调用了setRequestTimer，怀疑此调用使用了默认的timeout 120秒。而setRequestTimer方法里，似乎$request->whenComplete中调用timer的clearTimeout()调用没有检查timer id是否有效，另一处调用clearTimeout的是delTimer()，是否因不同途径调用产生的重复清除timer导致了此错误？

**Comment by andot** [comment]
非常感谢
