### ISSUE TITLE
如何做权限认证？

### ISSUE THREAD

**Issue by albertli2333** [hprose/hprose-php#81]
php多个函数需要用到权限验证，改如何去验证呢？

**Comment by andot** [comment]
统一验证可以通过[调用中间件](https://github.com/hprose/hprose-php/wiki/12-Hprose-%E4%B8%AD%E9%97%B4%E4%BB%B6#%E8%B0%83%E7%94%A8%E4%B8%AD%E9%97%B4%E4%BB%B6)来实现。通过验证调用 $next，没有通过验证不调用 $next，直接返回你想返回的错误信息就可以了。

**Comment by qwxingzhe** [comment]
> 统一验证可以通过[调用中间件](https://github.com/hprose/hprose-php/wiki/12-Hprose-%E4%B8%AD%E9%97%B4%E4%BB%B6#%E8%B0%83%E7%94%A8%E4%B8%AD%E9%97%B4%E4%BB%B6)来实现。通过验证调用 $next，没有通过验证不调用 $next，直接返回你想返回的错误信息就可以了。

请问中间件如何传参？

**Comment by wukaisheng91** [comment]
就希望建立连接时候验证，而不是后续每次调用的时候传参验证。

就这个问题。
不知道有没有人解决了，还是我们的思路错了？

**Comment by andot** [comment]
就建立连接的时候验证还不是很简单，你直接建立连接的时候通过参数传递不就可以了。

**Comment by wukaisheng91** [comment]
> 就建立连接的时候验证还不是很简单，你直接建立连接的时候通过参数传递不就可以了。

最近用多了，其实也就中间件最好了。其实每一次调用rpc方法都是重新开始的，客户端 new Client 时并不会立即就建立连接，只有在调用到rpc 中的方法时都会建立连接。
