### ISSUE TITLE
Onerror怎么用？

### ISSUE THREAD

**Issue by albertli2333** [hprose/hprose-php#88]
是这样的，我使用了addMissingFunction方式去做代理转发。但是呢，这个代理要远程调用的服务器可能会出问题，连不上或者其他奇怪的问题，那么我用怎么用onerror呢，文档感觉写得不是很好（请允许我吐槽一下）。我看到是在那么InvokeSettings那里调用，好像是回调函数，那么是否回调的return结果是否就是最后的处理结果呢，还有，这样的代理方式如何设置相应头呢？就是那个Status Code怎么设置呢

**Comment by andot** [comment]
onerror 有两种方式，一种是全局的事件。直接给客户端的 onError 属性赋值一个回调函数就可以了。另一种调用的时候，如果是同步调用，你就 try，异步调用你的 callback 写三个回调参数，第三个回调参数就是错误信息。
