### ISSUE TITLE
fclose(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by alonexy** [hprose/hprose-php#91]
/vendor/hprose/hprose/src/Hprose/Socket/Transporter.php(50)

`    public function __destruct() {
        if ($this->stream !== null) @fclose($this->stream);
    }`

**Comment by andot** [comment]
关闭之前，连接已经失效了。不过加了@应该不会显示出错误信息才对。

**Comment by alonexy** [comment]
`if(is_resource($this->stream)){
            @fclose($this->stream);
        }`
这样就不报了

**Comment by andot** [comment]
好主意，那就这么改
